// Code generated by protoc-gen-go.
// source: x-google-extensions.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	x-google-extensions.proto

It has these top-level messages:
	Any
	Book
	Document
	Shelve
	StringArray
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Any struct {
	Value *google_protobuf.Any `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *Any) Reset()                    { *m = Any{} }
func (m *Any) String() string            { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()               {}
func (*Any) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Any) GetValue() *google_protobuf.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type Book struct {
	Code    int64 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message int64 `protobuf:"varint,2,opt,name=message" json:"message,omitempty"`
}

func (m *Book) Reset()                    { *m = Book{} }
func (m *Book) String() string            { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()               {}
func (*Book) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Book) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Book) GetMessage() int64 {
	if m != nil {
		return m.Message
	}
	return 0
}

type Document struct {
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Shelve struct {
	Foo int64 `protobuf:"varint,1,opt,name=foo" json:"foo,omitempty"`
	Bar int64 `protobuf:"varint,2,opt,name=bar" json:"bar,omitempty"`
}

func (m *Shelve) Reset()                    { *m = Shelve{} }
func (m *Shelve) String() string            { return proto.CompactTextString(m) }
func (*Shelve) ProtoMessage()               {}
func (*Shelve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Shelve) GetFoo() int64 {
	if m != nil {
		return m.Foo
	}
	return 0
}

func (m *Shelve) GetBar() int64 {
	if m != nil {
		return m.Bar
	}
	return 0
}

type StringArray struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *StringArray) Reset()                    { *m = StringArray{} }
func (m *StringArray) String() string            { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()               {}
func (*StringArray) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StringArray) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Any)(nil), "main.Any")
	proto.RegisterType((*Book)(nil), "main.Book")
	proto.RegisterType((*Document)(nil), "main.Document")
	proto.RegisterType((*Shelve)(nil), "main.Shelve")
	proto.RegisterType((*StringArray)(nil), "main.StringArray")
}

func init() { proto.RegisterFile("x-google-extensions.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x45, 0x49, 0x27, 0x56, 0x7d, 0x51, 0x94, 0xa1, 0x8b, 0x56, 0x5c, 0xc8, 0x88, 0x52, 0x84,
	0x4e, 0x41, 0xbf, 0x20, 0x41, 0xf7, 0x85, 0x80, 0xfb, 0x49, 0xfb, 0x3a, 0x06, 0x93, 0xf7, 0xc2,
	0x24, 0x29, 0xcd, 0xef, 0xf8, 0xa5, 0xd2, 0x4e, 0x6a, 0xc0, 0xed, 0xbd, 0xe7, 0xc2, 0x3d, 0x30,
	0xdb, 0x2f, 0x2c, 0xb3, 0x2d, 0x70, 0x81, 0xfb, 0x06, 0xa9, 0xce, 0x99, 0x6a, 0x5d, 0x39, 0x6e,
	0x58, 0x86, 0xa5, 0xc9, 0xe9, 0x6e, 0xe6, 0xeb, 0xe5, 0x31, 0xcb, 0xda, 0xed, 0xd2, 0x50, 0xe7,
	0x01, 0xf5, 0x02, 0x22, 0xa6, 0x4e, 0x3e, 0xc2, 0xd9, 0xce, 0x14, 0x2d, 0x4e, 0x83, 0x87, 0x60,
	0x1e, 0xbd, 0x4e, 0xb4, 0x5f, 0xe8, 0xd3, 0x42, 0xc7, 0xd4, 0xa9, 0x27, 0x08, 0x13, 0xe6, 0x6f,
	0x79, 0x05, 0xe1, 0x9a, 0x37, 0x9e, 0x15, 0xf2, 0x06, 0xce, 0x4b, 0xac, 0x6b, 0x63, 0x71, 0x3a,
	0x3a, 0x04, 0x0a, 0xe0, 0xe2, 0x9d, 0xd7, 0x6d, 0x89, 0xd4, 0x28, 0x05, 0xe3, 0xf4, 0x0b, 0x8b,
	0x1d, 0xca, 0x08, 0xc4, 0x96, 0xb9, 0xdf, 0x44, 0x20, 0x32, 0xe3, 0x7a, 0xfe, 0x1e, 0xa2, 0xb4,
	0x71, 0x39, 0xd9, 0xd8, 0x39, 0xd3, 0xc9, 0xeb, 0xe1, 0x8a, 0x98, 0x5f, 0x26, 0x29, 0x3c, 0xb3,
	0xb3, 0x9a, 0x2b, 0x24, 0x53, 0xe5, 0xfa, 0xcf, 0xb0, 0x7f, 0x38, 0x18, 0x27, 0x93, 0x4f, 0xa4,
	0x0d, 0xbb, 0x8f, 0x53, 0xb2, 0x3a, 0x7c, 0x5f, 0x05, 0x3f, 0xa3, 0xdb, 0xff, 0x68, 0x36, 0x3e,
	0x7a, 0xbd, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0xff, 0x06, 0xfc, 0x27, 0x3a, 0x01, 0x00, 0x00,
}
