// Code generated by protoc-gen-go.
// source: vendorextension.proto
// DO NOT EDIT!

/*
Package vendorextension is a generated protocol buffer package.

It is generated from these files:
	vendorextension.proto

It has these top-level messages:
	Version
	VendorExtensionHandlerRequest
	VendorExtensionHandlerResponse
	Wrapper
*/
package vendorextension

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The version number of OpenAPI compiler.
type Version struct {
	Major int32 `protobuf:"varint,1,opt,name=major" json:"major,omitempty"`
	Minor int32 `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Patch int32 `protobuf:"varint,3,opt,name=patch" json:"patch,omitempty"`
	// A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
	// be empty for mainline stable releases.
	Suffix string `protobuf:"bytes,4,opt,name=suffix" json:"suffix,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Version) GetMajor() int32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *Version) GetMinor() int32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *Version) GetPatch() int32 {
	if m != nil {
		return m.Patch
	}
	return 0
}

func (m *Version) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

// An encoded PluginRequest is written to the plugin's stdin.
type VendorExtensionHandlerRequest struct {
	// The OpenAPI descriptions that were explicitly listed on the command line.
	// The specifications will appear in the order they are specified to openapic.
	Wrapper *Wrapper `protobuf:"bytes,1,opt,name=wrapper" json:"wrapper,omitempty"`
	// The plugin parameter passed on the command-line.
	Parameter string `protobuf:"bytes,2,opt,name=parameter" json:"parameter,omitempty"`
	// The version number of openapi compiler.
	CompilerVersion *Version `protobuf:"bytes,3,opt,name=compiler_version" json:"compiler_version,omitempty"`
}

func (m *VendorExtensionHandlerRequest) Reset()                    { *m = VendorExtensionHandlerRequest{} }
func (m *VendorExtensionHandlerRequest) String() string            { return proto.CompactTextString(m) }
func (*VendorExtensionHandlerRequest) ProtoMessage()               {}
func (*VendorExtensionHandlerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VendorExtensionHandlerRequest) GetWrapper() *Wrapper {
	if m != nil {
		return m.Wrapper
	}
	return nil
}

func (m *VendorExtensionHandlerRequest) GetParameter() string {
	if m != nil {
		return m.Parameter
	}
	return ""
}

func (m *VendorExtensionHandlerRequest) GetCompilerVersion() *Version {
	if m != nil {
		return m.CompilerVersion
	}
	return nil
}

// The plugin writes an encoded PluginResponse to stdout.
type VendorExtensionHandlerResponse struct {
	// Error message.  If non-empty, the plugin failed.
	// The plugin process should exit with status code zero
	// even if it reports an error in this way.
	//
	// This should be used to indicate errors which prevent the plugin from
	// operating as intended.  Errors which indicate a problem in openapic
	// itself -- such as the input Document being unparseable -- should be
	// reported by writing a message to stderr and exiting with a non-zero
	// status code.
	Error []string `protobuf:"bytes,1,rep,name=error" json:"error,omitempty"`
	// text output
	Value *google_protobuf.Any `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *VendorExtensionHandlerResponse) Reset()                    { *m = VendorExtensionHandlerResponse{} }
func (m *VendorExtensionHandlerResponse) String() string            { return proto.CompactTextString(m) }
func (*VendorExtensionHandlerResponse) ProtoMessage()               {}
func (*VendorExtensionHandlerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VendorExtensionHandlerResponse) GetError() []string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *VendorExtensionHandlerResponse) GetValue() *google_protobuf.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type Wrapper struct {
	// The filename or URL of the wrapped description
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The version of the OpenAPI specification that is used by the wrapped description.
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// Must be a valid yaml for the proto
	Yaml string `protobuf:"bytes,3,opt,name=yaml" json:"yaml,omitempty"`
}

func (m *Wrapper) Reset()                    { *m = Wrapper{} }
func (m *Wrapper) String() string            { return proto.CompactTextString(m) }
func (*Wrapper) ProtoMessage()               {}
func (*Wrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Wrapper) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Wrapper) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Wrapper) GetYaml() string {
	if m != nil {
		return m.Yaml
	}
	return ""
}

func init() {
	proto.RegisterType((*Version)(nil), "vendorextension.Version")
	proto.RegisterType((*VendorExtensionHandlerRequest)(nil), "vendorextension.VendorExtensionHandlerRequest")
	proto.RegisterType((*VendorExtensionHandlerResponse)(nil), "vendorextension.VendorExtensionHandlerResponse")
	proto.RegisterType((*Wrapper)(nil), "vendorextension.Wrapper")
}

func init() { proto.RegisterFile("vendorextension.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xbf, 0x42, 0xa6, 0xd5, 0xea, 0xa2, 0x10, 0x45, 0xa5, 0xc4, 0x4b, 0xbd, 0x6c,
	0xb1, 0x82, 0x9e, 0x5b, 0x51, 0xf4, 0xd4, 0x22, 0x52, 0x8f, 0xb2, 0x6d, 0xa7, 0x31, 0x92, 0xec,
	0xae, 0x93, 0x0f, 0xdb, 0x9f, 0xe1, 0x5f, 0xf0, 0x97, 0x4a, 0x77, 0xcd, 0x25, 0xe8, 0xf1, 0xdd,
	0x19, 0xf6, 0x79, 0xde, 0x81, 0xc3, 0x02, 0xe5, 0x52, 0x11, 0xae, 0x33, 0x94, 0x69, 0xa4, 0x24,
	0xd7, 0xa4, 0x32, 0xc5, 0xba, 0x95, 0xe7, 0xe3, 0xa3, 0x50, 0xa9, 0x30, 0xc6, 0x81, 0x19, 0xcf,
	0xf3, 0xd5, 0x40, 0xc8, 0x8d, 0xdd, 0x0d, 0xee, 0xc1, 0x9d, 0x21, 0x6d, 0xb7, 0xd8, 0x0e, 0x34,
	0x13, 0xf1, 0xae, 0xc8, 0x77, 0x7a, 0x4e, 0xbf, 0x69, 0x62, 0x24, 0x15, 0xf9, 0xb5, 0x32, 0x6a,
	0x91, 0x2d, 0xde, 0xfc, 0xba, 0x89, 0xbb, 0xd0, 0x4a, 0xf3, 0xd5, 0x2a, 0x5a, 0xfb, 0x8d, 0x9e,
	0xd3, 0xf7, 0x82, 0x2f, 0x07, 0x4e, 0x67, 0x06, 0x7b, 0x57, 0x62, 0x1f, 0x84, 0x5c, 0xc6, 0x48,
	0x4f, 0xf8, 0x91, 0x63, 0x9a, 0xb1, 0x0b, 0x70, 0x3f, 0x49, 0x68, 0x8d, 0x16, 0xd0, 0x1e, 0xfa,
	0xbc, 0xaa, 0xff, 0x62, 0xe7, 0x6c, 0x1f, 0x3c, 0x2d, 0x48, 0x24, 0x98, 0xa1, 0xc5, 0x7b, 0x6c,
	0x08, 0x7b, 0x0b, 0x95, 0xe8, 0x28, 0x46, 0x7a, 0x2d, 0xac, 0xb0, 0x31, 0xf9, 0xeb, 0x9b, 0xdf,
	0x42, 0xc1, 0x33, 0x9c, 0xfd, 0xa7, 0x94, 0x6a, 0x25, 0x53, 0xdc, 0x96, 0x42, 0x22, 0x53, 0xb9,
	0xde, 0xf7, 0xd8, 0x39, 0x34, 0x0b, 0x11, 0xe7, 0x68, 0x98, 0xed, 0xe1, 0x01, 0xb7, 0x77, 0xe3,
	0xe5, 0xdd, 0xf8, 0x48, 0x6e, 0x82, 0x6b, 0x70, 0x4b, 0xcf, 0x0e, 0x34, 0xa4, 0x48, 0xd0, 0xf4,
	0xf1, 0x58, 0x17, 0xdc, 0xd2, 0xcc, 0x3a, 0x77, 0xa0, 0xb1, 0x11, 0x49, 0x6c, 0x3c, 0xbd, 0xf1,
	0x0d, 0x74, 0x15, 0x85, 0x5c, 0x69, 0x94, 0x42, 0x47, 0x0b, 0x5e, 0x5c, 0x8e, 0x4f, 0x26, 0x1a,
	0xe5, 0x68, 0xfa, 0x58, 0xb1, 0x9c, 0xc6, 0x79, 0x18, 0xc9, 0xa9, 0xf3, 0x5d, 0xab, 0x4f, 0x46,
	0xb7, 0xf3, 0x96, 0xc1, 0x5f, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x49, 0x67, 0x1f, 0xee,
	0x01, 0x00, 0x00,
}
